"""
Bandwidth Allocation Service

Connects:

    Simulation
        ↓
    Game Theory
        ↓
    Nash Equilibrium
        ↓
    Fairness Evaluation

This module does NOT use external APIs.
All users are generated locally by the simulation module.
"""

from backend.game_theory.congestion_game import User
from backend.game_theory.nash_equilibrium import (
    find_nash_equilibrium
)
from backend.game_theory.fairness import (
    jains_fairness_index,
    fairness_status
)


# ============================================================
# CREATE GAME USERS
# ============================================================

def create_game_users(simulated_users):
    """
    Convert simulated users into Game Theory User objects.

    Parameters
    ----------
    simulated_users : list
        Users generated by user_generator.py.

    Returns
    -------
    list
        List of Game Theory User objects.
    """

    users = []

    for simulated_user in simulated_users:

        user = User(

            user_id=simulated_user["user_id"],

            activity=simulated_user["activity"],

            requested_bandwidth=
                simulated_user["requested_bandwidth"],

            latency=simulated_user.get(
                "latency", 0.0
            ),

            jitter=simulated_user.get(
                "jitter", 0.0
            )

        )

        users.append(user)

    return users


# ============================================================
# RUN BANDWIDTH ALLOCATION
# ============================================================

def allocate_bandwidth(
    simulated_users,
    total_bandwidth,
    congestion_penalty=0.5,
    step=0.5,
    max_iterations=100
):
    """
    Run the Game Theory bandwidth allocation.

    Parameters
    ----------
    simulated_users : list
        Users produced by the simulation.

    total_bandwidth : float
        Total available Wi-Fi bandwidth.

    congestion_penalty : float
        Penalty caused by network congestion.

    step : float
        Bandwidth search step used by the
        best-response algorithm.

    max_iterations : int
        Maximum Nash equilibrium iterations.

    Returns
    -------
    dict
        Complete allocation result.
    """

    # --------------------------------------------------------
    # Validate bandwidth
    # --------------------------------------------------------

    if total_bandwidth <= 0:

        raise ValueError(
            "Total bandwidth must be greater than zero."
        )


    # --------------------------------------------------------
    # Validate users
    # --------------------------------------------------------

    if not simulated_users:

        raise ValueError(
            "At least one user is required."
        )


    # --------------------------------------------------------
    # Convert simulation users into Game Theory players
    # --------------------------------------------------------

    users = create_game_users(
        simulated_users
    )


    # --------------------------------------------------------
    # Calculate total requested bandwidth
    # --------------------------------------------------------

    total_requested = sum(

        user.requested_bandwidth

        for user in users

    )


    # --------------------------------------------------------
    # Create the congestion game
    # --------------------------------------------------------

    # This object represents the complete game.
    #
    # Although Nash equilibrium performs the allocation,
    # creating the game object keeps the architecture
    # clear and allows us to use its utility functions
    # later.

    from backend.game_theory.congestion_game import (
        CongestionGame
    )

    game = CongestionGame(

        total_bandwidth=total_bandwidth,

        users=users,

        congestion_penalty=
            congestion_penalty

    )


    # --------------------------------------------------------
    # Find approximate Nash equilibrium
    # --------------------------------------------------------

    nash_result = find_nash_equilibrium(

        users=users,

        total_bandwidth=
            total_bandwidth,

        congestion_penalty=
            congestion_penalty,

        step=step,

        max_iterations=
            max_iterations

    )


    # --------------------------------------------------------
    # Get final allocations
    # --------------------------------------------------------

    allocations = (
        nash_result["allocations"]
    )


    iterations = (
        nash_result["iterations"]
    )


    # --------------------------------------------------------
    # Calculate total allocated bandwidth
    # --------------------------------------------------------

    total_allocated = sum(
        allocations.values()
    )


    # --------------------------------------------------------
    # Calculate bandwidth utilization
    # --------------------------------------------------------

    utilization = (

        total_allocated
        / total_bandwidth
    ) * 100


    utilization = round(
        utilization,
        2
    )


    # --------------------------------------------------------
    # Calculate fairness
    # --------------------------------------------------------

    fairness_index = (
        jains_fairness_index(
            allocations
        )
    )


    fairness_label = (
        fairness_status(
            fairness_index
        )
    )


    # --------------------------------------------------------
    # Calculate final utilities
    # --------------------------------------------------------

    game.calculate_utilities()


    # --------------------------------------------------------
    # Prepare user results
    # --------------------------------------------------------

    user_results = []

    for user in users:

        user_results.append({

            "user_id":
                user.user_id,

            "activity":
                user.activity,

            "requested_bandwidth":
                round(
                    user.requested_bandwidth,
                    2
                ),

            "allocated_bandwidth":
                round(
                    user.allocated_bandwidth,
                    2
                ),

            "utility":
                round(
                    user.utility,
                    4
                ),

            "activity_weight":
                user.weight

        })


    # --------------------------------------------------------
    # Return complete result
    # --------------------------------------------------------

    return {

        "total_bandwidth":
            round(
                total_bandwidth,
                2
            ),

        "total_requested_bandwidth":
            round(
                total_requested,
                2
            ),

        "total_allocated_bandwidth":
            round(
                total_allocated,
                2
            ),

        "unused_bandwidth":
            round(
                max(
                    total_bandwidth
                    - total_allocated,
                    0
                ),
                2
            ),

        "utilization_percentage":
            utilization,

        "jain_fairness_index":
            fairness_index,

        "fairness_status":
            fairness_label,

        "iterations":
            iterations,

        "convergence_iterations":
            iterations,

        "converged":
            iterations < max_iterations,

        "is_nash_equilibrium":
            nash_result.get(
                "is_nash_equilibrium",
                False
            ),

        "users":
            user_results

    }


# ============================================================
# DISPLAY RESULTS
# ============================================================

def display_allocation_result(
    result
):
    """
    Display allocation results in the terminal.
    """

    print()

    print("=" * 70)

    print(
        "       SMART WI-FI BANDWIDTH SHARING"
    )

    print("=" * 70)

    print()

    print(
        f"Total Available Bandwidth : "
        f"{result['total_bandwidth']:.2f} Mbps"
    )

    print(
        f"Total Requested Bandwidth : "
        f"{result['total_requested_bandwidth']:.2f} Mbps"
    )

    print(
        f"Total Allocated Bandwidth : "
        f"{result['total_allocated_bandwidth']:.2f} Mbps"
    )

    print(
        f"Unused Bandwidth          : "
        f"{result['unused_bandwidth']:.2f} Mbps"
    )

    print()

    print("-" * 70)

    print(
        "USER BANDWIDTH ALLOCATION"
    )

    print("-" * 70)

    for user in result["users"]:

        print(

            f"User {user['user_id']:<3}"

            f"| Activity: "
            f"{user['activity']:<15}"

            f"| Requested: "
            f"{user['requested_bandwidth']:>7.2f} Mbps"

            f" | Allocated: "
            f"{user['allocated_bandwidth']:>7.2f} Mbps"

            f" | Utility: "
            f"{user['utility']:>7.4f}"

        )


    print()

    print("-" * 70)

    print(
        f"Bandwidth Utilization : "
        f"{result['utilization_percentage']:.2f}%"
    )

    print(
        f"Jain Fairness Index   : "
        f"{result['jain_fairness_index']:.4f}"
    )

    print(
        f"Fairness Status       : "
        f"{result['fairness_status']}"
    )

    print(
        f"Iterations             : "
        f"{result['iterations']}"
    )

    print("-" * 70)


# ============================================================
# TEST THE SERVICE
# ============================================================

if __name__ == "__main__":

    # Import our synthetic traffic generator.

    from backend.simulation.traffic_generator import (
        generate_traffic_scenario
    )


    # --------------------------------------------------------
    # Generate a simulated network
    # --------------------------------------------------------

    scenario = generate_traffic_scenario(

        scenario="medium",

        seed=42

    )


    # --------------------------------------------------------
    # Run Game Theory allocation
    # --------------------------------------------------------

    result = allocate_bandwidth(

        simulated_users=
            scenario["users"],

        total_bandwidth=
            scenario["total_bandwidth"],

        congestion_penalty=0.5,

        step=0.5,

        max_iterations=100

    )


    # --------------------------------------------------------
    # Display results
    # --------------------------------------------------------

    display_allocation_result(
        result
    )