"""
Data Provenance Constants

Every metric shown by the application must be identifiable as one of:

REAL_DATASET
    Derived from the real packet-capture dataset (Cleaned_Dataset.csv)
    or processed_users.csv.

REAL_RUNTIME_MEASUREMENT
    Measured from the running system at runtime (e.g. CPU, memory,
    actual network interface counters). Not currently available on
    all platforms, so most network metrics fall back to SIMULATION.

CALCULATED_FROM_REAL_DATA
    Computed from real inputs using a deterministic algorithm.
    Examples: Nash allocation, Jain Fairness Index, utilization.

SIMULATION
    Generated by the research simulation engine for demonstration
    or experimental purposes. Must be clearly labeled in the UI.

USER_INPUT
    Provided directly by a human user via the UI.
"""
REAL_DATASET = "REAL_DATASET"
REAL_RUNTIME_MEASUREMENT = "REAL_RUNTIME_MEASUREMENT"
CALCULATED_FROM_REAL_DATA = "CALCULATED_FROM_REAL_DATA"
REAL_USER_INPUT = "REAL_USER_INPUT"
SIMULATION = "SIMULATION"
RESEARCH_SIMULATION = "RESEARCH_SIMULATION"
USER_INPUT = "USER_INPUT"
UNAVAILABLE = "UNAVAILABLE"
