import { useMemo } from "react";
import { motion } from "framer-motion";
import { BandwidthLine, ConsumptionBar, CategoryDoughnut, AllocationPie, AppCategoryBar } from "../components/Charts";
import { useLiveUsers } from "../hooks/useLiveUsers";
import { useNetworkStats } from "../hooks/useNetworkStats";
import DataSourceLabel from "../components/DataSourceLabel";
import { REAL_RUNTIME_MEASUREMENT, RESEARCH_SIMULATION, CALCULATED_FROM_REAL_DATA } from "../data/provenance";
import "../styles/pages.css";

export default function Analytics() {
  const { users } = useLiveUsers();
  const { history } = useNetworkStats();

  const categoryData = useMemo(() => {
    const counts = {};
    users.forEach((u) => {
      if (u.status !== "offline") {
        counts[u.device] = (counts[u.device] || 0) + 1;
      }
    });
    const labels = Object.keys(counts);
    const palette = ["#2563eb", "#7c3aed", "#14b8a6", "#f59e0b", "#ef4444", "#3b82f6", "#8b5cf6", "#06b6d4"];
    return {
      labels,
      datasets: [
        {
          data: Object.values(counts),
          backgroundColor: labels.map((_, i) => palette[i % palette.length]),
          borderRadius: 8,
        },
      ],
    };
  }, [users]);

  const totalAllocated = useMemo(
    () => users.reduce((s, u) => s + (u.allocated || 0), 0),
    [users]
  );

  return (
    <motion.div
      className="page"
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
    >
      <div className="page-head">
        <div>
          <h2 className="page-title">📈 Analytics</h2>
          <p className="text-dim">Network insights · Device data is simulated · Host throughput is real in LIVE mode</p>
        </div>
        <DataSourceLabel source={RESEARCH_SIMULATION} />
      </div>

      <div className="sim-banner glass">
        <strong>Research Simulation Mode</strong>
        <p>
          The charts below combine two different data sources:
          <br />
          • <strong>Host throughput</strong> — real local measurement when LIVE mode is enabled.
          <br />
          • <strong>Device categories, user consumption, allocation share, and app categories</strong> —
          controlled research simulation. These results are generated by the simulation engine and
          must not be interpreted as measurements from a physical Wi-Fi network.
        </p>
      </div>

      {/* Line — full width */}
      <div className="chart-card glass">
        <div className="chart-head">
          <h3 className="section-title"><span className="dot" /> Host Throughput</h3>
          <DataSourceLabel source={REAL_RUNTIME_MEASUREMENT} />
        </div>
        <div className="chart-body tall">
          <BandwidthLine history={history} />
        </div>
      </div>

      {/* Bar + Doughnut */}
      <div className="grid-2">
        <div className="chart-card glass">
          <div className="chart-head">
            <h3 className="section-title"><span className="dot" /> User Consumption</h3>
            <DataSourceLabel source={RESEARCH_SIMULATION} />
          </div>
          <div className="chart-body">
            <ConsumptionBar users={users} />
          </div>
        </div>

        <div className="chart-card glass">
          <div className="chart-head">
            <h3 className="section-title"><span className="dot" /> Device Category</h3>
            <DataSourceLabel source={RESEARCH_SIMULATION} />
          </div>
          <div className="chart-body">
            <CategoryDoughnut users={users} />
          </div>
        </div>
      </div>

      {/* Pie full width-ish */}
      <div className="chart-card glass">
        <div className="chart-head">
          <h3 className="section-title"><span className="dot" /> Bandwidth Allocation Share</h3>
          <DataSourceLabel source={RESEARCH_SIMULATION} />
        </div>
        <div className="chart-body pie-wide">
          <AllocationPie users={users} />
        </div>
      </div>

      {/* Category bar */}
      <div className="chart-card glass">
        <div className="chart-head">
          <h3 className="section-title"><span className="dot" /> Traffic by Application Category</h3>
          <DataSourceLabel source={RESEARCH_SIMULATION} />
        </div>
        <div className="chart-body">
          <AppCategoryBar data={categoryData} />
        </div>
      </div>
    </motion.div>
  );
}